## Reto 1: Hundir la Flota (Batalla Naval)
### Objetivo: Implementar una versión simplificada del juego de Batalla Naval usando Python y Numpy para manejar el tablero del juego.

- Crear un tablero 10x10 usando Numpy arrays.
- Colocar 5 barcos de diferentes tamaños en posiciones aleatorias en el tablero.
- Permitir que el jugador ingrese coordenadas para "disparar".
- Mostrar un mensaje si el jugador acierta o falla, y actualizar el tablero acorde.
- Seguir jugando hasta que todos los barcos sean hundidos.
#### Habilidades aplicadas: Uso de arrays de Numpy, generación de números aleatorios, estructuras de control en Python.

## Reto 2: Tres en Raya (Tic-Tac-Toe)
### Objetivo: Implementar el juego de Tres en Raya.

- Crear un tablero 3x3 usando Numpy arrays.
- Permitir a dos jugadores ingresar sus movimientos alternadamente.
- Verificar después de cada movimiento si alguno de los jugadores ha ganado.
- Mostrar el tablero después de cada turno.
- Terminar el juego si hay un ganador o si el tablero está lleno.
#### Habilidades aplicadas: Manipulación de arrays, estructuras de control, funciones en Python.

## Reto 3: Torres de Hanoi
### Objetivo: Implementar el juego de las Torres de Hanoi usando Python.

- Crear tres pilas para representar los tres postes del juego.
- Implementar la lógica para mover un disco de un poste a otro, siguiendo las reglas del juego.
- Desarrollar una función recursiva para resolver el juego.
- Permitir al usuario elegir el número de discos con los que jugará.
#### Habilidades aplicadas: Recursividad, estructuras de datos (pilas), funciones en Python.

``Deberas hacer por lo menos uno de los tres para de la fecha de entrega, pero antes de terminar el modulo de analisis de datos tendras que entregar todos..``

como se cual debo hacer muy simple introduce tu fecha de cumpleaños en la siguiente funcion

In [3]:
def cual_es_mi_reto(fecha: str) -> str:
    """
    Args:
    ------
    fecha: str el formato de la fecha es DD-MM-YYYY
    Returns:
    -------
    str: el numero del reto
    """
    try:
        return int(fecha.split('-')[0]) % 3
    except:
        return 'La fecha tiene que ser en este formato DD-MM-YYYY'

In [4]:
cual_es_mi_reto(fecha='08-04-1989')

2

In [17]:
import numpy as np

torre = np.array([[1,0,0], 
                 [2,0,0],
                 [3,0,0],
                 [4,0,0]])
print(torre)

[[1 0 0]
 [2 0 0]
 [3 0 0]
 [4 0 0]]


In [27]:
discos = 4
torre[discos -1][0]

4

In [34]:
discos = 4
o = np.arange(1,discos + 1).reshape(discos,1)
d_a = np.full((discos,2), 0)

np.hstack([o,d_a])


array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0],
       [4, 0, 0]])

In [37]:
def torre_hanoi(discos = 6):
    o = np.arange(1,discos + 1).reshape(discos,1)
    d_a = np.full((discos,2), 0)
    torres = np.hstack([o,d_a])
    print(torres)
    def mover_discos(discos, origen, auxiliar, destino):
        if torres.sum(axis=0)[0] == 1:
            torres[3][0] = 0
            torres[0][3] = 1
    

torre_hanoi()

[[1 0 0]
 [2 0 0]
 [3 0 0]
 [4 0 0]
 [5 0 0]
 [6 0 0]]


In [ ]:
def mover_torres(n, origen, auxiliar, destino):
    if n == 1:
        print(f"Mueve el disco 1 de {origen} a {destino}")
        return
    mover_torres(n-1, origen, destino, auxiliar)
    print(f"Mueves el disco {n} de {origen} a {destino}")
    mover_torres(n-1, auxiliar, origen, destino)

n = 3
mover_torres(n, 'A', 'B', 'C')

: 