# Operar con datos en Pandas

Una de las piezas esenciales de NumPy es la capacidad de realizar operaciones rápidas elemento a elemento, tanto con aritmética básica (suma, resta, multiplicación, etc.) como con operaciones más sofisticadas (funciones trigonométricas, funciones exponenciales y logarítmicas, etc.).
**Pandas hereda gran parte de esta funcionalidad de NumPy, y las ufuncs** que introdujimos en [Computation on NumPy Arrays: Universal Functions](3_Computation-on-arrays-ufuncs.ipynb) son clave para ello.

Pandas incluye un par de giros útiles, sin embargo: para operaciones unarias como negación y funciones trigonométricas, estas ufuncs *preservarán las etiquetas de índice y columna* en la salida, y para operaciones binarias como **adición y multiplicación, Pandas *alineará automáticamente los índices* al pasar los objetos a la ufunc.**
Esto significa que mantener el contexto de los datos y combinar datos de diferentes fuentes -ambas tareas potencialmente propensas a errores con arrays NumPy sin procesar- se convierten en tareas esencialmente infalibles con Pandas.
Además, veremos que hay operaciones bien definidas entre estructuras unidimensionales ``Series`` y estructuras bidimensionales ``DataFrame``.

## Ufuncs: Índice Preservación

Como Pandas está diseñado para trabajar con NumPy, cualquier ufunc de NumPy funcionará con los objetos ``Series`` y ``DataFrame`` de Pandas.
Empecemos definiendo una ``Series`` y un ``DataFrame`` simples para demostrarlo:

In [1]:
import pandas as pd
import numpy as np

In [5]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [14]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  1  0  6  6
1  7  4  2  7
2  5  2  0  2

Si aplicamos una ufunc NumPy sobre cualquiera de estos objetos, el resultado será otro objeto Pandas *con los índices conservados:*

In [15]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

O, para un cálculo un poco más complejo:

In [19]:
np.sin(df * np.pi / 4)

A             B    C         D
0  0.707107  0.000000e+00 -1.0 -1.000000
1 -0.707107  1.224647e-16  1.0 -0.707107
2 -0.707107  1.000000e+00  0.0  1.000000

Cualquiera de las ufuncs discutidas en [Computation on NumPy Arrays: Universal Functions](3_Computation-on-arrays-ufuncs.ipynb) puede ser usada de forma similar.

## UFuncs: Index Alignment

Para operaciones binarias sobre dos objetos ``Series`` o ``DataFrame``, Pandas alineará los índices en el proceso de realización de la operación.
Esto es muy conveniente cuando se trabaja con datos incompletos, como veremos en algunos de los ejemplos que siguen.

### Alineación del índice en la serie

Como ejemplo, supongamos que estamos combinando dos fuentes de datos diferentes, y encontramos sólo los tres primeros estados de EE.UU. por *área* y los tres primeros estados de EE.UU. por *población*:

In [21]:
area = pd.Series({'Alaska': 1723337,
                  'Texas': 695662,
                  'California': 423967},
                 name='area')

population = pd.Series({'California': 38332521,
                        'Texas': 26448193,
                        'New York': 19651127},
                       name='population')

Veamos qué ocurre cuando los dividimos para calcular la densidad de población:

In [22]:
type(population / area)

pandas.core.series.Series

In [27]:
s_poblacion_area = population / area
print(s_poblacion_area)

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64


La matriz resultante contiene la *unión* de los índices de las dos matrices de entrada, que podría determinarse utilizando la aritmética de conjuntos estándar de Python sobre estos índices:

In [24]:
area.index

Index(['Alaska', 'Texas', 'California'], dtype='object')

In [25]:
population.index

Index(['California', 'Texas', 'New York'], dtype='object')

In [26]:
area.index | population.index

C:\Users\Mega Tecnologia\AppData\Local\Temp\ipykernel_11796\3572280633.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  area.index | population.index


Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [28]:
area.index.union(population.index)

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

Cualquier elemento para el que uno u otro no tenga una entrada se marca con ``NaN``, o "Not a Number", que es como Pandas marca los datos que faltan (ver más discusión sobre datos que faltan en [Handling Missing Data](4_Missing-Values.ipynb)).
Esta coincidencia de índices se implementa de esta forma para cualquiera de las expresiones aritméticas incorporadas en Python; cualquier valor que falte se rellena con NaN por defecto:

In [30]:
A = pd.Series([2, 4, 6], index=["andalucia", "aragon", "madrid"])
print(A)
B = pd.Series([1, 3, 5], index=["aragon", "madrid", "asturias"])
print(B)
A + B

andalucia    2
aragon       4
madrid       6
dtype: int64
aragon      1
madrid      3
asturias    5
dtype: int64


andalucia    NaN
aragon       5.0
asturias     NaN
madrid       9.0
dtype: float64

In [32]:
df_AB = pd.DataFrame({'n_alumnos': A, 'n_profesores': B})
df_AB

n_alumnos  n_profesores
andalucia        2.0           NaN
aragon           4.0           1.0
asturias         NaN           5.0
madrid           6.0           3.0

In [33]:
# df_AB = pd.DataFrame({'n_alumnos': A, 'n_profesores': B})
df_AB['n_personas'] = df_AB['n_alumnos'] + df_AB['n_profesores']
df_AB

n_alumnos  n_profesores  n_personas
andalucia        2.0           NaN         NaN
aragon           4.0           1.0         5.0
asturias         NaN           5.0         NaN
madrid           6.0           3.0         9.0

In [38]:
df_AB['n_alumnos_10'] = df_AB['n_alumnos'] * 10
df_AB

n_alumnos  n_profesores  n_personas  n_alumnos_10
andalucia        2.0           NaN         NaN          20.0
aragon           4.0           1.0         5.0          40.0
asturias         NaN           5.0         NaN           NaN
madrid           6.0           3.0         9.0          60.0

Si el uso de valores NaN no es el comportamiento deseado, el valor de relleno puede modificarse utilizando métodos de objeto apropiados en lugar de los operadores.
Por ejemplo, llamar a ``A.add(B)`` es equivalente a llamar a ``A + B``, pero permite la especificación explícita opcional del valor de relleno para cualquier elemento de ``A`` o ``B`` que pueda faltar:

In [39]:
B + A

andalucia    NaN
aragon       5.0
asturias     NaN
madrid       9.0
dtype: float64

In [40]:
print(A)
print(B)

andalucia    2
aragon       4
madrid       6
dtype: int64
aragon      1
madrid      3
asturias    5
dtype: int64


In [41]:
A.add(B, fill_value=0)

andalucia    2.0
aragon       5.0
asturias     5.0
madrid       9.0
dtype: float64

### Alineación de índices en DataFrame

Un tipo similar de alineación tiene lugar para *ambos* columnas e índices cuando se realizan operaciones en ``DataFrame``s:

In [42]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0   4  14
1  13   2

In [43]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  0  4  9
1  6  6  8
2  9  9  2

In [54]:
A + B #rellena el valor en el data frame final pero no en cada DF

A     B   C
0   8.0  14.0 NaN
1  19.0   8.0 NaN
2   NaN   NaN NaN

In [50]:
C.fillna('hola')

A     B     C
0   8.0  14.0  hola
1  19.0   8.0  hola
2  hola  hola  hola

Observe que los índices se alinean correctamente independientemente de su orden en los dos objetos, y que los índices del resultado están ordenados.
Como en el caso de ``Series``, podemos utilizar el método aritmético del objeto asociado y pasarle cualquier ``valor_de_relleno`` que queramos utilizar en lugar de las entradas que falten.
Aquí rellenaremos con la media de todos los valores de ``A`` (calculada apilando primero las filas de ``A``):

In [51]:
fill = A.values.mean()
A.add(B, fill_value=fill) #rellena el valor antes de hacer la operación y después los suma

A      B      C
0   8.00  14.00  17.25
1  19.00   8.00  16.25
2  17.25  17.25  10.25

La siguiente tabla lista los operadores de Python y sus métodos equivalentes en los objetos de Pandas:

| Python Operador | Pandas Method(s)                      |
|-----------------|---------------------------------------|
| ``+``           | ``add()``                             |
| ``-``           | ``sub()``, ``subtract()``             |
| ``*``           | ``mul()``, ``multiply()``             |
| ``/``           | ``truediv()``, ``div()``, ``divide()``|
| ``//``          | ``floordiv()``                        |
| ``%``           | ``mod()``                             |
| ``**``          | ``pow()``                             |


## Ufuncs: Operaciones entre DataFrame y Series

Cuando se realizan operaciones entre un ``DataFrame`` y una ``Series``, la alineación de índices y columnas se mantiene de forma similar.
Las operaciones entre un ``DataFrame`` y una ``Series`` son similares a las operaciones entre un array NumPy bidimensional y unidimensional.
Consideremos una operación común, donde encontramos la diferencia de un array bidimensional y una de sus filas:

In [55]:
A = rng.randint(10, size=(3, 4))
A

array([[6, 0, 3, 3],
       [4, 6, 6, 3],
       [6, 2, 5, 1]])

In [56]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-2,  6,  3,  0],
       [ 0,  2,  2, -2]])

In [57]:
A[0]

array([6, 0, 3, 3])

Según las reglas de difusión de NumPy (véase [Computación en matrices: difusión](5_Computation-on-arrays-broadcasting.ipynb)), la resta entre una matriz bidimensional y una de sus filas se aplica fila a fila.

En Pandas, la convención opera de forma similar por defecto:

In [63]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -2  6  3  0
2  0  2  2 -2

Si, por el contrario, desea operar por columnas, puede utilizar los métodos de objeto mencionados anteriormente, especificando la palabra clave ``axis``:

In [66]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  6  0  3  3
1 -2  0  0 -3
2  4  0  3 -1

Tenga en cuenta que estas operaciones ``DataFrame``/``Series``, al igual que las operaciones comentadas anteriormente, alinearán automáticamente los índices entre los dos elementos:

In [67]:
df

Q  R  S  T
0  6  0  3  3
1  4  6  6  3
2  6  2  5  1

In [69]:
halfrow = df.iloc[0, ::2]
halfrow

Q    6
S    3
Name: 0, dtype: int32

In [70]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -2.0 NaN  3.0 NaN
2  0.0 NaN  2.0 NaN

Esta preservación y alineación de índices y columnas significa que las operaciones sobre datos en Pandas siempre mantendrán el contexto de los datos, lo que previene los tipos de errores tontos que podrían surgir al trabajar con datos heterogéneos y/o desalineados en arrays NumPy sin procesar.